### ISSUE TITLE
line 208 - keyError: 'results'

### ISSUE THREAD

**Issue by lecocqe** [gromk/vw-offline-manual-creator#1]
Hello,

i have the following error. trying to download a manual: Traceback (most recent call last):
  File "vw-offline-manual-creator.py", line 208, in <module>
    manuals = j3['results']
KeyError: 'results'
...

can you help me ?

Best regards

**Comment by gromk** [comment]
> 
> 
> Hello,
> 
> i have the following error. trying to download a manual: Traceback (most recent call last):
> File "vw-offline-manual-creator.py", line 208, in
> manuals = j3['results']
> KeyError: 'results'
> ...
> 
> can you help me ?
> 
> Best regards

Hello Eric,
I tested the script just now with my own VIN number, and it worked just fine.
Can you please share your value for the parameter {vehicle_id} ?
Best regards.

**Comment by lecocqe** [comment]
Hello,

Vehicle id is ok. triple checked.
when debugging the data. at line 208:

# Request for the list of available manuals
r3 = http_session.get(f"https://userguide.volkswagen.de/api/web/V3/search?query=&facetfilters=topic-type_|_welcome&lang={lang}&page=0&pageSize=20")
j3 = r3.json()

Value of j3 is: {'path': '/api/web/V3/search', 'errorMessage': 'Full authentication is required to access this resource', 'errorCode': '401'}

best regards.

**Comment by gromk** [comment]
What happens when you input your vehicle ID directly on the online service at https://userguide.volkswagen.de/public/vin/login/en_GB ?

**Comment by lecocqe** [comment]
![image](https://user-images.githubusercontent.com/18657222/118646053-fcb14c80-b7df-11eb-8db4-447b08410675.png)

**Comment by lecocqe** [comment]
i have to goto https://userguide.volkswagen.de/public/vin/login/fr_FR to get it on line

**Comment by lecocqe** [comment]
![image](https://user-images.githubusercontent.com/18657222/118646417-78ab9480-b7e0-11eb-9c77-88723a9bf959.png)

**Comment by gromk** [comment]
> i have to goto https://userguide.volkswagen.de/public/vin/login/fr_FR to get it on line

Well then please please to change line 197 accordingly. I am using VW online service from France, maybe there are restrictions/different access rules from Belgium?

Tell me if it helps.

**Comment by lecocqe** [comment]
No it doesn't work. 
do you have some documentation about api of vw or how did you do the "reverse" engineering to create your script ?

**Comment by gromk** [comment]
There is no such thing as an API. I did reverse engineering, examining all the HTTP requests in the browser.
Basically, your request to "scrap" the manual contents (line 208) fail because you did not authenticated successfully prior to it. When using a web browser, you enter your VIN on the welcome page and in response, the server sets a session cookie, BEFORE displaying the manual pages. This cookie is sent along with all the subsequent HTTP requests, saying "this user has a valid VIN, you can deliver the payload". In your case, for some reason, this cookie is not set by the server. Unfortunately, without your VIN number, I cannot reproduce your problem. Do you have a way to share it privately? Or publicly, but temporarily?

**Comment by lecocqe** [comment]
ok, send me an email to lecocqe@outlook.com. i will answer with the VIN. 
Thank you for your time.

**Comment by gromk** [comment]
@lecocqe Thank you for your help. I fixed the issue, which was caused by your manual being considered "legacy" (maybe meaning: pre-2018 or pre-2019). 
See PR #2
You should now be able to download your manual without error. I'll wait for your answer before closing the issue.

**Comment by lecocqe** [comment]
i just ran the new version.
i had to install lxml: https://lxml.de/installation.html 
then run just fine with a little exception at the end. I sent you privately the logs generated.

thanks a lot for the fast reaction

**Comment by deb75** [comment]
Hi,

I have a very similar error : 
```
Traceback (most recent call last):
  File "C:\Users\xxx\work\vw-offline-manual-creator\vw-offline-manual-creator.py", line 224, in <module>
    manuals = j3["results"]
KeyError: 'results'
```
and `print(j3)` yields : 
```
{'path': '/api/web/V3/search', 'errorMessage': 'ERR_01_001_TP', 'errorCode': 404}
```

My vin number works on the page [https://userguide.volkswagen.de/public/vin/login/fr_FR](https://userguide.volkswagen.de/public/vin/login/fr_FR) and I can navigate freely in the manual.

A change in the wolkswagen api ?

Regards

**Comment by gromk** [comment]
This error suggests that the URLs were updated on the VW website.
I think that PR #3 fixes the issue (merged today, 27 Apr 2025).

**Comment by zarhan** [comment]
I have encountered this same authorization problem now - the first http request results in 401. Locale is FI, and car is Id.Polo. I can read it just fine via VW's site on a browser. I can provide VIN if needed.
